name: Publish avitools
# Controls when the action will run. 
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: harbor-repo.vmware.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: avinetworks/avitools
      - name: Echo
        run: echo ${{ steps.meta.outputs.tags }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Build and push Docker image
        run: |
          docker build . --tag harbor-repo.vmware.com/nsx_alb_tools/${{ steps.get_version.outputs.VERSION }}:${{ steps.meta.outputs.tags }}
          docker run harbor-repo.vmware.com/nsx_alb_tools/${{ steps.get_version.outputs.VERSION }}:${{ steps.meta.outputs.tags }}
          docker push harbor-repo.vmware.com/nsx_alb_tools/${{ steps.get_version.outputs.VERSION }}:${{ steps.meta.outputs.tags }}


          
      
      
